# SPDX-License-Identifier: BSD-3-Clause
"""Generate the bsdsocket.library LVO vector table from the NDK sfd.

Reads sfd/bsdsocket_lib.sfd and writes src/bsdsocket/vectors.c: the complete
function table in exact LVO order, every slot pointing at LibStub until the
real implementation lands. ==varargs entries are C-glue aliases of the
preceding slot (no LVO of their own); ==reserve N emits N stub slots.

Run manually from the repo root when the sfd changes:
    python3 scripts/gen-vectors.py
The output is checked in, so the Amiga build has no generator dependency.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SFD = ROOT / "sfd" / "bsdsocket_lib.sfd"
OUT = ROOT / "src" / "bsdsocket" / "vectors.c"

# LVO name -> implementing symbol (declared in sb_base.h). Everything else
# stays on LibStub until its implementation lands.
IMPLEMENTED = {
    "socket": "bsd_socket",
    "bind": "bsd_bind",
    "listen": "bsd_listen",
    "accept": "bsd_accept",
    "connect": "bsd_connect",
    "sendto": "bsd_sendto",
    "send": "bsd_send",
    "recvfrom": "bsd_recvfrom",
    "recv": "bsd_recv",
    "shutdown": "bsd_shutdown",
    "setsockopt": "bsd_setsockopt",
    "getsockopt": "bsd_getsockopt",
    "getsockname": "bsd_getsockname",
    "getpeername": "bsd_getpeername",
    "IoctlSocket": "bsd_IoctlSocket",
    "CloseSocket": "bsd_CloseSocket",
    "WaitSelect": "bsd_WaitSelect",
    "SetSocketSignals": "bsd_SetSocketSignals",
    "getdtablesize": "bsd_getdtablesize",
    "Errno": "bsd_Errno",
    "SetErrnoPtr": "bsd_SetErrnoPtr",
    "Inet_NtoA": "bsd_Inet_NtoA",
    "inet_addr": "bsd_inet_addr",
    "Inet_LnaOf": "bsd_Inet_LnaOf",
    "Inet_NetOf": "bsd_Inet_NetOf",
    "Inet_MakeAddr": "bsd_Inet_MakeAddr",
    "inet_network": "bsd_inet_network",
    "gethostbyname": "bsd_gethostbyname",
    "gethostbyaddr": "bsd_gethostbyaddr",
    "gethostname": "bsd_gethostname",
    "gethostid": "bsd_gethostid",
    "SocketBaseTagList": "bsd_SocketBaseTagList",
    "inet_aton": "bsd_inet_aton",
    "inet_ntop": "bsd_inet_ntop",
    "inet_pton": "bsd_inet_pton",
    "getprotobyname": "bsd_getprotobyname",
    "getprotobynumber": "bsd_getprotobynumber",
    "Dup2Socket": "bsd_Dup2Socket",
    "sendmsg": "bsd_sendmsg",
    "recvmsg": "bsd_recvmsg",
    "vsyslog": "bsd_vsyslog",
    "ObtainSocket": "bsd_ObtainSocket",
    "ReleaseSocket": "bsd_ReleaseSocket",
    "ReleaseCopyOfSocket": "bsd_ReleaseCopyOfSocket",
    "getservbyname": "bsd_getservbyname",
    "getservbyport": "bsd_getservbyport",
    "getnetbyname": "bsd_getnetbyname",
    "getnetbyaddr": "bsd_getnetbyaddr",
    "setnetent": "bsd_setnetent",
    "endnetent": "bsd_endnetent",
    "getnetent": "bsd_getnetent",
    "setprotoent": "bsd_setprotoent",
    "endprotoent": "bsd_endprotoent",
    "getprotoent": "bsd_getprotoent",
    "setservent": "bsd_setservent",
    "endservent": "bsd_endservent",
    "getservent": "bsd_getservent",
    "gethostbyname_r": "bsd_gethostbyname_r",
    "gethostbyaddr_r": "bsd_gethostbyaddr_r",
    "In_LocalAddr": "bsd_In_LocalAddr",
    "In_CanForward": "bsd_In_CanForward",
    "AddDomainNameServer": "bsd_AddDomainNameServer",
    "RemoveDomainNameServer": "bsd_RemoveDomainNameServer",
    "ObtainDomainNameServerList": "bsd_ObtainDomainNameServerList",
    "ReleaseDomainNameServerList": "bsd_ReleaseDomainNameServerList",
    "GetDefaultDomainName": "bsd_GetDefaultDomainName",
    "SetDefaultDomainName": "bsd_SetDefaultDomainName",
    "freeaddrinfo": "bsd_freeaddrinfo",
    "getaddrinfo": "bsd_getaddrinfo",
    "gai_strerror": "bsd_gai_strerror",
    "getnameinfo": "bsd_getnameinfo",
    "GetSocketEvents": "bsd_GetSocketEvents",
}

# Unimplemented LVOs that return POINTERS get the NULL stub; handing an app
# LibStub's -1 where it checks for NULL would be a crash.
NULL_STUBS = {
    "mbuf_copym", "mbuf_free", "mbuf_get", "mbuf_gethdr", "mbuf_prepend",
    "mbuf_pullup", "GetRouteInfo", "ObtainInterfaceList", "ObtainRoadshowData",
}

HEADER = """\
/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * bsdsocket.library LVO vector table — GENERATED by scripts/gen-vectors.py
 * from sfd/bsdsocket_lib.sfd (NDK 3.2R4). Do not edit by hand; regenerate.
 *
 * Implemented LVOs point at their bsd_* functions (see the IMPLEMENTED map
 * in the generator); the rest stay on LibStub. The table length and order
 * are the ABI — apps call by LVO offset.
 */

#include <exec/types.h>

#include "sb_base.h"

const APTR bsdsocket_functable[] = {
    (APTR)LibOpen,    /*   -6 */
    (APTR)LibClose,   /*  -12 */
    (APTR)LibExpunge, /*  -18 */
    (APTR)LibNull,    /*  -24 */
"""

FOOTER = """\
    (APTR)-1};
"""


def main():
    slots = []  # (name, is_reserved)
    varargs_pending = False
    bias = None

    for raw in SFD.read_text(errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("*"):
            continue
        if line.startswith("=="):
            directive = line[2:].split(None, 1)
            key = directive[0].lower()
            if key == "bias":
                bias = int(directive[1])
            elif key == "reserve":
                for _ in range(int(directive[1])):
                    slots.append(("reserved", True))
            elif key == "varargs":
                varargs_pending = True
            continue
        if "(" not in line:
            continue
        head = line.split("(", 1)[0].replace("*", " ").strip()
        name = head.split()[-1]
        if not re.fullmatch(r"[A-Za-z_]\w*", name):
            sys.exit(f"cannot parse function name from: {raw!r}")
        if varargs_pending:
            # varargs alias of the previous slot: C glue only, no LVO
            varargs_pending = False
            continue
        slots.append((name, False))

    if bias != 30:
        sys.exit(f"unexpected ==bias {bias} (expected 30)")

    lines = [HEADER]
    for i, (name, reserved) in enumerate(slots):
        offset = bias + 6 * i
        tag = f"(reserved)" if reserved else name
        default = "LibStubNull" if name in NULL_STUBS else "LibStub"
        sym = "LibStub" if reserved else IMPLEMENTED.get(name, default)
        lines.append(f"    (APTR){sym}, /* -{offset:<4d} {tag} */\n")
    lines.append(FOOTER)
    OUT.write_text("".join(lines))
    print(f"{OUT.relative_to(ROOT)}: {len(slots)} LVO slots, last at -{bias + 6 * (len(slots) - 1)}")


if __name__ == "__main__":
    main()
