/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * bsdsocket.library LVO vector table — GENERATED by scripts/gen-vectors.py
 * from sfd/bsdsocket_lib.sfd (NDK 3.2R4). Do not edit by hand; regenerate.
 *
 * Implemented LVOs point at their bsd_* functions (see the IMPLEMENTED map
 * in the generator); the rest stay on LibStub. The table length and order
 * are the ABI — apps call by LVO offset.
 */

#include <exec/types.h>

#include "sb_base.h"

const APTR bsdsocket_functable[] = {
    (APTR)LibOpen,    /*   -6 */
    (APTR)LibClose,   /*  -12 */
    (APTR)LibExpunge, /*  -18 */
    (APTR)LibNull,    /*  -24 */
    (APTR)bsd_socket, /* -30   socket */
    (APTR)bsd_bind, /* -36   bind */
    (APTR)bsd_listen, /* -42   listen */
    (APTR)bsd_accept, /* -48   accept */
    (APTR)bsd_connect, /* -54   connect */
    (APTR)bsd_sendto, /* -60   sendto */
    (APTR)bsd_send, /* -66   send */
    (APTR)bsd_recvfrom, /* -72   recvfrom */
    (APTR)bsd_recv, /* -78   recv */
    (APTR)bsd_shutdown, /* -84   shutdown */
    (APTR)bsd_setsockopt, /* -90   setsockopt */
    (APTR)bsd_getsockopt, /* -96   getsockopt */
    (APTR)bsd_getsockname, /* -102  getsockname */
    (APTR)bsd_getpeername, /* -108  getpeername */
    (APTR)bsd_IoctlSocket, /* -114  IoctlSocket */
    (APTR)bsd_CloseSocket, /* -120  CloseSocket */
    (APTR)bsd_WaitSelect, /* -126  WaitSelect */
    (APTR)bsd_SetSocketSignals, /* -132  SetSocketSignals */
    (APTR)bsd_getdtablesize, /* -138  getdtablesize */
    (APTR)bsd_ObtainSocket, /* -144  ObtainSocket */
    (APTR)bsd_ReleaseSocket, /* -150  ReleaseSocket */
    (APTR)bsd_ReleaseCopyOfSocket, /* -156  ReleaseCopyOfSocket */
    (APTR)bsd_Errno, /* -162  Errno */
    (APTR)bsd_SetErrnoPtr, /* -168  SetErrnoPtr */
    (APTR)bsd_Inet_NtoA, /* -174  Inet_NtoA */
    (APTR)bsd_inet_addr, /* -180  inet_addr */
    (APTR)bsd_Inet_LnaOf, /* -186  Inet_LnaOf */
    (APTR)bsd_Inet_NetOf, /* -192  Inet_NetOf */
    (APTR)bsd_Inet_MakeAddr, /* -198  Inet_MakeAddr */
    (APTR)bsd_inet_network, /* -204  inet_network */
    (APTR)bsd_gethostbyname, /* -210  gethostbyname */
    (APTR)bsd_gethostbyaddr, /* -216  gethostbyaddr */
    (APTR)bsd_getnetbyname, /* -222  getnetbyname */
    (APTR)bsd_getnetbyaddr, /* -228  getnetbyaddr */
    (APTR)bsd_getservbyname, /* -234  getservbyname */
    (APTR)bsd_getservbyport, /* -240  getservbyport */
    (APTR)bsd_getprotobyname, /* -246  getprotobyname */
    (APTR)bsd_getprotobynumber, /* -252  getprotobynumber */
    (APTR)bsd_vsyslog, /* -258  vsyslog */
    (APTR)bsd_Dup2Socket, /* -264  Dup2Socket */
    (APTR)bsd_sendmsg, /* -270  sendmsg */
    (APTR)bsd_recvmsg, /* -276  recvmsg */
    (APTR)bsd_gethostname, /* -282  gethostname */
    (APTR)bsd_gethostid, /* -288  gethostid */
    (APTR)bsd_SocketBaseTagList, /* -294  SocketBaseTagList */
    (APTR)bsd_GetSocketEvents, /* -300  GetSocketEvents */
    (APTR)LibStub, /* -306  (reserved) */
    (APTR)LibStub, /* -312  (reserved) */
    (APTR)LibStub, /* -318  (reserved) */
    (APTR)LibStub, /* -324  (reserved) */
    (APTR)LibStub, /* -330  (reserved) */
    (APTR)LibStub, /* -336  (reserved) */
    (APTR)LibStub, /* -342  (reserved) */
    (APTR)LibStub, /* -348  (reserved) */
    (APTR)LibStub, /* -354  (reserved) */
    (APTR)LibStub, /* -360  (reserved) */
    (APTR)LibStub, /* -366  bpf_open */
    (APTR)LibStub, /* -372  bpf_close */
    (APTR)LibStub, /* -378  bpf_read */
    (APTR)LibStub, /* -384  bpf_write */
    (APTR)LibStub, /* -390  bpf_set_notify_mask */
    (APTR)LibStub, /* -396  bpf_set_interrupt_mask */
    (APTR)LibStub, /* -402  bpf_ioctl */
    (APTR)LibStub, /* -408  bpf_data_waiting */
    (APTR)LibStub, /* -414  AddRouteTagList */
    (APTR)LibStub, /* -420  DeleteRouteTagList */
    (APTR)LibStub, /* -426  ChangeRouteTagList */
    (APTR)LibStub, /* -432  FreeRouteInfo */
    (APTR)LibStubNull, /* -438  GetRouteInfo */
    (APTR)bsd_InterfaceConfigUnsupported, /* -444  AddInterfaceTagList */
    (APTR)bsd_InterfaceConfigUnsupported, /* -450  ConfigureInterfaceTagList */
    (APTR)bsd_ReleaseInterfaceList, /* -456  ReleaseInterfaceList */
    (APTR)bsd_ObtainInterfaceList, /* -462  ObtainInterfaceList */
    (APTR)bsd_QueryInterfaceTagList, /* -468  QueryInterfaceTagList */
    (APTR)LibStubNull, /* -474  CreateAddrAllocMessageA */
    (APTR)LibStub, /* -480  DeleteAddrAllocMessage */
    (APTR)LibStub, /* -486  BeginInterfaceConfig */
    (APTR)LibStub, /* -492  AbortInterfaceConfig */
    (APTR)LibStub, /* -498  AddNetMonitorHookTagList */
    (APTR)LibStub, /* -504  RemoveNetMonitorHook */
    (APTR)LibStub, /* -510  GetNetworkStatistics */
    (APTR)bsd_AddDomainNameServer, /* -516  AddDomainNameServer */
    (APTR)bsd_RemoveDomainNameServer, /* -522  RemoveDomainNameServer */
    (APTR)bsd_ReleaseDomainNameServerList, /* -528  ReleaseDomainNameServerList */
    (APTR)bsd_ObtainDomainNameServerList, /* -534  ObtainDomainNameServerList */
    (APTR)bsd_setnetent, /* -540  setnetent */
    (APTR)bsd_endnetent, /* -546  endnetent */
    (APTR)bsd_getnetent, /* -552  getnetent */
    (APTR)bsd_setprotoent, /* -558  setprotoent */
    (APTR)bsd_endprotoent, /* -564  endprotoent */
    (APTR)bsd_getprotoent, /* -570  getprotoent */
    (APTR)bsd_setservent, /* -576  setservent */
    (APTR)bsd_endservent, /* -582  endservent */
    (APTR)bsd_getservent, /* -588  getservent */
    (APTR)bsd_inet_aton, /* -594  inet_aton */
    (APTR)bsd_inet_ntop, /* -600  inet_ntop */
    (APTR)bsd_inet_pton, /* -606  inet_pton */
    (APTR)bsd_In_LocalAddr, /* -612  In_LocalAddr */
    (APTR)bsd_In_CanForward, /* -618  In_CanForward */
    (APTR)LibStubNull, /* -624  mbuf_copym */
    (APTR)LibStub, /* -630  mbuf_copyback */
    (APTR)LibStub, /* -636  mbuf_copydata */
    (APTR)LibStubNull, /* -642  mbuf_free */
    (APTR)LibStub, /* -648  mbuf_freem */
    (APTR)LibStubNull, /* -654  mbuf_get */
    (APTR)LibStubNull, /* -660  mbuf_gethdr */
    (APTR)LibStubNull, /* -666  mbuf_prepend */
    (APTR)LibStub, /* -672  mbuf_cat */
    (APTR)LibStub, /* -678  mbuf_adj */
    (APTR)LibStubNull, /* -684  mbuf_pullup */
    (APTR)LibStub, /* -690  ProcessIsServer */
    (APTR)LibStub, /* -696  ObtainServerSocket */
    (APTR)bsd_GetDefaultDomainName, /* -702  GetDefaultDomainName */
    (APTR)bsd_SetDefaultDomainName, /* -708  SetDefaultDomainName */
    (APTR)LibStubNull, /* -714  ObtainRoadshowData */
    (APTR)LibStub, /* -720  ReleaseRoadshowData */
    (APTR)LibStub, /* -726  ChangeRoadshowData */
    (APTR)bsd_InterfaceConfigUnsupported, /* -732  RemoveInterface */
    (APTR)bsd_gethostbyname_r, /* -738  gethostbyname_r */
    (APTR)bsd_gethostbyaddr_r, /* -744  gethostbyaddr_r */
    (APTR)LibStub, /* -750  (reserved) */
    (APTR)LibStub, /* -756  (reserved) */
    (APTR)LibStub, /* -762  ipf_open */
    (APTR)LibStub, /* -768  ipf_close */
    (APTR)LibStub, /* -774  ipf_ioctl */
    (APTR)LibStub, /* -780  ipf_log_read */
    (APTR)LibStub, /* -786  ipf_log_data_waiting */
    (APTR)LibStub, /* -792  ipf_set_notify_mask */
    (APTR)LibStub, /* -798  ipf_set_interrupt_mask */
    (APTR)bsd_freeaddrinfo, /* -804  freeaddrinfo */
    (APTR)bsd_getaddrinfo, /* -810  getaddrinfo */
    (APTR)bsd_gai_strerror, /* -816  gai_strerror */
    (APTR)bsd_getnameinfo, /* -822  getnameinfo */
    (APTR)LibStub, /* -828  (reserved) */
    (APTR)LibStub, /* -834  (reserved) */
    (APTR)LibStub, /* -840  (reserved) */
    (APTR)LibStub, /* -846  (reserved) */
    (APTR)LibStub, /* -852  (reserved) */
    (APTR)LibStub, /* -858  (reserved) */
    (APTR)-1};
